loglevel: debug # 日志级别 info debug disable error fatal warn 等等
host: 127.0.0.1 # host 地址
port: 80
maxsize: 1024  # 文件上传限制
pprof: false #  http://localhost:8086/debug/pprof/heap ...
cache:
  driver: local # 缓存驱动 local redis
limit:
  disable: true
  limit: 2 # 每秒允许请求 1 次
  burst: 10 # 最高允许并发
redis:
  host: localhost
  port: 6379
  password:
